// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9T_EO4ZswwwdaQezc6vZ_5HMhDltdej4',
    appId: '1:607192763630:web:9ca88d1ad00c1b3a98b7ff',
    messagingSenderId: '607192763630',
    projectId: 'floodcare-b6adf',
    authDomain: 'floodcare-b6adf.firebaseapp.com',
    storageBucket: 'floodcare-b6adf.firebasestorage.app',
    measurementId: 'G-V6V2N6PY8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCykh-jlAYuzHdxare2KTgMjWaX5VQQK7w',
    appId: '1:607192763630:android:ed0076e52622455c98b7ff',
    messagingSenderId: '607192763630',
    projectId: 'floodcare-b6adf',
    storageBucket: 'floodcare-b6adf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFmRVL3qakfmfBQdIQFbGXCikVLJ5PkC8',
    appId: '1:607192763630:ios:c1f7e4adde7c549498b7ff',
    messagingSenderId: '607192763630',
    projectId: 'floodcare-b6adf',
    storageBucket: 'floodcare-b6adf.firebasestorage.app',
    iosBundleId: 'com.example.floodcareMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFmRVL3qakfmfBQdIQFbGXCikVLJ5PkC8',
    appId: '1:607192763630:ios:c1f7e4adde7c549498b7ff',
    messagingSenderId: '607192763630',
    projectId: 'floodcare-b6adf',
    storageBucket: 'floodcare-b6adf.firebasestorage.app',
    iosBundleId: 'com.example.floodcareMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9T_EO4ZswwwdaQezc6vZ_5HMhDltdej4',
    appId: '1:607192763630:web:c292a438fa20b36898b7ff',
    messagingSenderId: '607192763630',
    projectId: 'floodcare-b6adf',
    authDomain: 'floodcare-b6adf.firebaseapp.com',
    storageBucket: 'floodcare-b6adf.firebasestorage.app',
    measurementId: 'G-CZZCQSTTB2',
  );
}
